on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Build and deploy'
        uses: tsg-iitkgp/next-build-export-action@main
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
